# DoIt theme version
version = "0.4.0"

description = "Personal blog"

[app]
	title = "hashp4"
	noFavicon = false
	svgFavicon = "/favicon.ico"
	themeColor = "#ffffff"
	iconColor = "#5bbad5"
	tileColor = "#da532c"

[author]
	name = "hashp4"
	email = ""
	link = "https://hashp4.fr"
	avatar = "/images/logo.png"


[search]
	enable = false
	type = "lunr"
	contentLength = 4000
	placeholder = ""
	maxResultLength = 10
	snippetLength = 30
	highlightTag = "em"
	absoluteURL = false

[home]
	rss = 10
	[home.profile]
		enable = true
		avatarURL = "/images/logo.png"
		title = "hashp4"
		subtitle = "Cyberdefense Engineer - MILF CTF Team Captain"
		typeit = true
		social = true
		disclaimer = ""
	[home.posts]
		enable = true
		paginate = 5

[social]
	github = "hashp4"
	linkedin = "enzo-saez"
	twitter = "hashp4_"
	hackthebox = "295290"
	tryhackme = "RB28Z2"
	milfctf = "."
